name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 'latest-stable'
    
    - name: Cache Swift packages
      uses: actions/cache@v4
      with:
        path: .build
        key: ${{ runner.os }}-swift-${{ hashFiles('Package.swift') }}
        restore-keys: |
          ${{ runner.os }}-swift-
    
    - name: Build debug
      run: swift build
      
    - name: Run tests
      run: swift test --parallel
      
    - name: Build release
      run: swift build -c release
      
    - name: Test CLI functionality
      run: |
        echo "Testing CLI help command..."
        .build/release/geotagger --help
        
        echo "Testing CLI version command..."
        .build/release/geotagger --version
        
        echo "Testing invalid arguments (should fail gracefully)..."
        .build/release/geotagger --invalid-arg || echo "Expected failure handled correctly"